#pragma once
#include <string>
#include <unordered_map>

// ISO 3166-1 alpha-2 country names (lowercase keys)
static const std::unordered_map<std::string, std::string> COUNTRIES = {
    {"ad","Andorra"},{"ae","United Arab Emirates"},{"af","Afghanistan"},
    {"ag","Antigua and Barbuda"},{"al","Albania"},{"am","Armenia"},
    {"ao","Angola"},{"ar","Argentina"},{"at","Austria"},{"au","Australia"},
    {"aw","Aruba"},{"az","Azerbaijan"},{"ba","Bosnia and Herzegovina"},
    {"bb","Barbados"},{"bd","Bangladesh"},{"be","Belgium"},{"bg","Bulgaria"},
    {"bh","Bahrain"},{"bm","Bermuda"},{"bn","Brunei"},{"bo","Bolivia"},
    {"br","Brazil"},{"bs","Bahamas"},{"bt","Bhutan"},{"bw","Botswana"},
    {"by","Belarus"},{"bz","Belize"},{"ca","Canada"},{"cd","DR Congo"},
    {"ch","Switzerland"},{"ci","Ivory Coast"},{"cl","Chile"},{"cm","Cameroon"},
    {"cn","China"},{"co","Colombia"},{"cr","Costa Rica"},{"cu","Cuba"},
    {"cv","Cape Verde"},{"cy","Cyprus"},{"cz","Czechia"},{"de","Germany"},
    {"dj","Djibouti"},{"dk","Denmark"},{"do","Dominican Republic"},
    {"dz","Algeria"},{"ec","Ecuador"},{"ee","Estonia"},{"eg","Egypt"},
    {"er","Eritrea"},{"es","Spain"},{"et","Ethiopia"},{"fi","Finland"},
    {"fj","Fiji"},{"fr","France"},{"ga","Gabon"},{"gb","United Kingdom"},
    {"ge","Georgia"},{"gh","Ghana"},{"gi","Gibraltar"},{"gm","Gambia"},
    {"gn","Guinea"},{"gq","Equatorial Guinea"},{"gr","Greece"},
    {"gt","Guatemala"},{"gu","Guam"},{"gy","Guyana"},{"hk","Hong Kong"},
    {"hn","Honduras"},{"hr","Croatia"},{"ht","Haiti"},{"hu","Hungary"},
    {"id","Indonesia"},{"ie","Ireland"},{"il","Israel"},{"im","Isle of Man"},
    {"in","India"},{"iq","Iraq"},{"ir","Iran"},{"is","Iceland"},{"it","Italy"},
    {"jm","Jamaica"},{"jo","Jordan"},{"jp","Japan"},{"ke","Kenya"},
    {"kg","Kyrgyzstan"},{"kh","Cambodia"},{"km","Comoros"},{"kr","South Korea"},
    {"kw","Kuwait"},{"ky","Cayman Islands"},{"kz","Kazakhstan"},
    {"la","Laos"},{"lb","Lebanon"},{"lc","Saint Lucia"},{"li","Liechtenstein"},
    {"lk","Sri Lanka"},{"lr","Liberia"},{"lt","Lithuania"},{"lu","Luxembourg"},
    {"lv","Latvia"},{"ly","Libya"},{"ma","Morocco"},{"mc","Monaco"},
    {"md","Moldova"},{"me","Montenegro"},{"mg","Madagascar"},
    {"mk","North Macedonia"},{"ml","Mali"},{"mm","Myanmar"},{"mn","Mongolia"},
    {"mo","Macao"},{"mr","Mauritania"},{"mt","Malta"},{"mu","Mauritius"},
    {"mv","Maldives"},{"mw","Malawi"},{"mx","Mexico"},{"my","Malaysia"},
    {"mz","Mozambique"},{"na","Namibia"},{"ne","Niger"},{"ng","Nigeria"},
    {"ni","Nicaragua"},{"nl","Netherlands"},{"no","Norway"},{"np","Nepal"},
    {"nz","New Zealand"},{"om","Oman"},{"pa","Panama"},{"pe","Peru"},
    {"pg","Papua New Guinea"},{"ph","Philippines"},{"pk","Pakistan"},
    {"pl","Poland"},{"pr","Puerto Rico"},{"ps","Palestine"},{"pt","Portugal"},
    {"py","Paraguay"},{"qa","Qatar"},{"ro","Romania"},{"rs","Serbia"},
    {"ru","Russia"},{"rw","Rwanda"},{"sa","Saudi Arabia"},{"sd","Sudan"},
    {"se","Sweden"},{"sg","Singapore"},{"si","Slovenia"},{"sk","Slovakia"},
    {"sl","Sierra Leone"},{"sm","San Marino"},{"sn","Senegal"},{"so","Somalia"},
    {"sr","Suriname"},{"ss","South Sudan"},{"sv","El Salvador"},{"sy","Syria"},
    {"sz","Eswatini"},{"td","Chad"},{"tg","Togo"},{"th","Thailand"},
    {"tj","Tajikistan"},{"tm","Turkmenistan"},{"tn","Tunisia"},
    {"tr","Turkey"},{"tt","Trinidad and Tobago"},{"tw","Taiwan"},
    {"tz","Tanzania"},{"ua","Ukraine"},{"ug","Uganda"},{"us","United States"},
    {"uy","Uruguay"},{"uz","Uzbekistan"},{"va","Vatican City"},
    {"ve","Venezuela"},{"vg","British Virgin Islands"},{"vi","US Virgin Islands"},
    {"vn","Vietnam"},{"ye","Yemen"},{"za","South Africa"},{"zm","Zambia"},
    {"zw","Zimbabwe"}
};

// US state codes used in WG2-US-XX-NNN wireguard filenames
static const std::unordered_map<std::string, std::string> US_STATES = {
    {"AL","Alabama"},{"AK","Alaska"},{"AZ","Arizona"},{"AR","Arkansas"},
    {"CA","California"},{"CO","Colorado"},{"CT","Connecticut"},{"DE","Delaware"},
    {"FL","Florida"},{"GA","Georgia"},{"HI","Hawaii"},{"ID","Idaho"},
    {"IL","Illinois"},{"IN","Indiana"},{"IA","Iowa"},{"KS","Kansas"},
    {"KY","Kentucky"},{"LA","Louisiana"},{"ME","Maine"},{"MD","Maryland"},
    {"MA","Massachusetts"},{"MI","Michigan"},{"MN","Minnesota"},
    {"MS","Mississippi"},{"MO","Missouri"},{"MT","Montana"},{"NE","Nebraska"},
    {"NV","Nevada"},{"NH","New Hampshire"},{"NJ","New Jersey"},{"NM","New Mexico"},
    {"NY","New York"},{"NC","North Carolina"},{"ND","North Dakota"},
    {"OH","Ohio"},{"OK","Oklahoma"},{"OR","Oregon"},{"PA","Pennsylvania"},
    {"RI","Rhode Island"},{"SC","South Carolina"},{"SD","South Dakota"},
    {"TN","Tennessee"},{"TX","Texas"},{"UT","Utah"},{"VT","Vermont"},
    {"VA","Virginia"},{"WA","Washington"},{"WV","West Virginia"},
    {"WI","Wisconsin"},{"WY","Wyoming"},{"DC","District of Columbia"}
};
